### ISSUE TITLE
Build instructions on README?

### ISSUE THREAD

**Issue by f03lipe** [viking-sudo-rm/SpokenWord#8]
Looking good. Is there a way to build this without Eclipse?

**Comment by f03lipe** [comment]
Or is there a way to provide the build so people can check it out without having to install Eclipse?

**Comment by viking-sudo-rm** [comment]
Yeah, you can get the latest build under "Releases" when you go to the code page.

Here's the link: https://github.com/viking-sudo-rm/SpokenWord/releases.

**Comment by f03lipe** [comment]
My bad! Thanks.

**Comment by viking-sudo-rm** [comment]
Oops, the most recent jar builds didn't work at all due to an issue with paths inside the .jar file system getting messed up. From now on, you can just download the source zip associated with each release and run the file `thoth.jar`.
