### ISSUE TITLE
Can't move again if game is closed and reopened

### ISSUE THREAD

**Issue by WingofaGriffin** [viking-sudo-rm/SpokenWord#9]
Reproduction: Open jar file, play tutorial. Close the game. Reopen the jar file and open tutorial again, character cannot move.

Played on Mac 10.10.5 in build 0.8.5

**Comment by viking-sudo-rm** [comment]
I can't reproduce this bug with the dev JAR I'm playing right now (commit 99a72be). Hopefully that means it will go away in next version.
